### PR TITLE
Added compact view

### PR DESCRIPTION
**Pull request by Virtual4087**
Issue : #4 

Added compact view feature.
And also there was a bug with the full/compact toggle button. You need to click twice to change view from full to compact after reloading the page so i fixed that too.

### CODE REVIEW

**Comment by Virtual4087** [comment]
Can you check it once?

**Comment by Jan-Fcloud** [comment]
> Can you check it once?

Beautiful solution, all I'd like to ask you to do is sync your pull with the current version of the repo, and it'll be good to go! :)

**Comment by Virtual4087** [comment]
Oops

**Comment by Virtual4087** [comment]
I'll fork it again

**Pull request closed without merging**
