### PR TITLE
Create 404 Page

### PR DESCRIPTION
**Pull request by NsCracker**
Design a 404 page in the style of the main Hacktoberfest website with the text 'Uh oh, you hacked too far...' and a button to return to the home screen. 
Please take a moment to review it.
#7 

image

### CODE REVIEW

**Comment by Jan-Fcloud** [comment]
Love the 404 page, I went ahead and made very slight changes for it to work with github pages and I set the menu link back since we don't want it to lead to 404 directly.

**Comment by NsCracker** [comment]
@Jan-Fcloud, thank you for merging. Unfortunately, the downside for me is that your repository is excluded from Hacktoberfest.

**Comment by Jan-Fcloud** [comment]
Hi @NsCracker , thank you very much for bringing this to my attention. I'll see what I can do about it. I believe the repo got mistaken for the average "add your profile and your done" repository.

If there is no other way of getting it back to be approved, I will be making a new one with a slightly different approach and additional rules so it would fit the event better.

You're very much welcome to recontribute the 404 page to the new repository **if** I will need to make a new one. If you wish, I can let you know if that becomes the case.

**Comment by NsCracker** [comment]
Sure, please keep me informed about the same.

**Pull request merged**
